---
- name: Play with_items
  hosts: pub
  gather_facts: true
  become_user: root
  tasks:
    - name: copy files
      copy:
        src: "{{item}}"
        dest: /var/www/html/{{item}}
        owner: root
        group: root
        mode: "0755"
      with_items:
        - index.html
        - script.js
        - style.css
