---
- name: Playbook to install Nginx on Webservers
  hosts: pub
  become: yes
  tasks:
    - name: Perform Apt update and Install basic packages
      shell: apt update && apt install -y unzip jq net-tools

    - name: Install Nginx Packages
      apt:
        name: nginx
        state: latest

    - name: Start nginx Service
      shell: systemctl start nginx
