---
- name: Playbook to install Nginx on Webservers
  hosts: server01
  become: yes
  gather_facts: yes
  tasks:
    - name: Perform Apt update and Install basic packages
      shell: apt update && apt install -y unzip jq net-tools
      when: (ansible_facts['distribution'] == "Ubuntu" and ansible_facts['distribution_version' == '20.04'])

    - name: Install Nginx Packages
      apt:
        name: nginx
        state: latest

    - name: Start nginx Service
      shell: systemctl start nginx
